name: Deploy to ECS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout Code
    - name: Checkout Code
      uses: actions/checkout@v3

    # Step 2: Log in to Amazon ECR
    - name: Log in to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    # Step 3: Build and Push Docker Image to ECR
    - name: Build, Tag, and Push Docker Image
      run: |
        IMAGE_URI=216989096072.dkr.ecr.us-east-1.amazonaws.com/my-python-app:latest
        
        docker build -t $IMAGE_URI .
        docker push $IMAGE_URI

    # Step 4: Update ECS Service with New Task Definition
    - name: Deploy to ECS Service
      uses: aws-actions/amazon-ecs-deploy-task-definition@v1
      with:
        task-definition: my-python-app-task.json # Optional if you want to update task definition dynamically
        service-name: my-python-app-service
        cluster-name: my-project-cluster
        wait-for-service-stability: true
