name: Build and DeploY

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
    - name: Checkout code
      uses: actions/checkout@v4  

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3  

    - name: Configure AWS credentials (Required for ECR)
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1  
        
    - name: Log in to AWS ECR
      uses: aws-actions/amazon-ecr-login@v2  

    - name: Log in to GHCR
      uses: docker/login-action@v3 
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push to GHCR
      uses: docker/build-push-action@v5  
      with:
        context: .
        push: true
        tags: |
          ghcr.io/${{ github.repository }}:latest

    - name: Build and push to ECR
      run: |
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:latest .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest
      env:
        ECR_REGISTRY: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com
        ECR_REPOSITORY: my-python-app
